### PR TITLE
Decode non-utf8 charset correctly

### PR DESCRIPTION
**Pull request by WindzCUHK**
## issue
cannot extract title from non-UTF8 HTML page correctly

## fix
read `<meta charset="...">` tag and decode with correctly encoding

### CODE REVIEW

**Comment by thom4parisot** [comment]
Great thank you!

Unfortunately I do not work at the BBC anymore, therefore I do not have write/merge permissions.

If someone is watching, please act accordingly :-)

**Comment by chrisn** [comment]
Many thanks @WindzCUHK for your contribution and to you @oncletom for the review!

**Comment by WindzCUHK** [comment]
@chrisn Can you help to release on [npm](https://www.npmjs.com/package/get-title)?
Seems it is not updated.

**Comment by chrisn** [comment]
Version 1.1.2 is now published to npm.

**Pull request merged**
